export enum SupportTypes {
    COMPANIONSHIP_AND_TRANSPORT =  "Acompanhamento e Transporte",
    MAINTENANCE_AND_REPAIRS =  "Manutenção e Reparo",
    TEACHING_AND_TECHNOLOGY  =  "Ensino e Tecnologia",
    SOCIAL_ACTIVITIES =  "Atividades Sociais",
    PHYSICAL_ACTIVITIES =  "Atividades Físicas",
}

export enum SupportTypesCodes {
    COMPANIONSHIP_AND_TRANSPORT = "COMPANIONSHIP_AND_TRANSPORT",
    MAINTENANCE_AND_REPAIRS = "MAINTENANCE_AND_REPAIRS",
    TEACHING_AND_TECHNOLOGY = "TEACHING_AND_TECHNOLOGY",
    SOCIAL_ACTIVITIES = "SOCIAL_ACTIVITIES",
    PHYSICAL_ACTIVITIES = "PHYSICAL_ACTIVITIES",
  }