@startuml
class User {
  id: number
  username: string
  cpf: string
  password: string
  email: string
  name: string
  birthdate: date
  address: Address
  taskList: Task[]
  description: string
  userType: 
}

class Address {
  id: number
  zip: string
  street: string
  number: number
  suite: string
  city: string
  district: string
  state: string
}

class SupportType {
 id: number
 type: ENUM
}

class Volunteer {
 supportTypes: SupportType[]
}

class Senior {
 
}

class Task {
id: number
title: string
supportType: SupportType
isOnline: boolean
description: string
date: date
time: datetime
status: string
seniorID: Senior
volunteerID: Volunteer
candidatesID: Volunteer[]
assessmentID: Assement 
}

class Assement {
id: number
grade: number
comment: string
taskID: string
} 


User "1" *-- "1" Address : has
Volunteer <|-- User : inherits
Senior <|-- User : inherits
@enduml
