version: '3.8'
services:
  backend:
    image: maven:3.8.4-jdk-11 # Usa uma imagem com Maven j치 instalado
    volumes:
      - .:/app  # Monta o diret칩rio atual no container
    working_dir: /app # Define o diret칩rio onde o projeto est치
    command: mvn test  # Executa o comando de teste diretamente
    depends_on:
      - db  # Espera o banco de dados inicializar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_db
      SPRING_DATASOURCE_USERNAME: postgrestest
      SPRING_DATASOURCE_PASSWORD: passwordtest

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: