version: '3.8'
services:
  backend:
    image: maven:3.9.9-eclipse-temurin-21 
    volumes:
      - .:/app 
    working_dir: /app
    command: mvn test
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_db
      SPRING_DATASOURCE_USERNAME: postgrestest
      SPRING_DATASOURCE_PASSWORD: passwordtest

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgrestest
      POSTGRES_PASSWORD: passwordtest
      POSTGRES_DB: test_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: